---
- name: install n8n on docker2
  hosts: docker2.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: n8n
        image: docker.n8n.io/n8nio/n8n
        pull: true
        hostname: n8n
        restart_policy: always
        networks:
          - name: web
        env:
          GENERIC_TIMEZONE: "Europe/London"
          TZ: "Europe/London"
          N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
          N8N_RUNNERS_ENABLED: "true"
        volumes:
          - n8n_data:/home/node/.n8n
        labels:
          caddy: n8n.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.import_1: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 5678 }}"
    - name: Create n8n.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: n8n.home.thunderweb.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200