---
- name: install wordpress on docker0.srv.3fr.uk for dev.scottclark.uk
  hosts: docker0.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: wordpress_dev_scottclark
        image: wordpress:php8.3-fpm
        pull: true
        hostname: wordpress_dev_scottclark
        restart_policy: always
        networks:
          - name: web
        env:
          TZ: "Europe/London"
          WORDPRESS_DB_HOST: "mariadb"
          WORDPRESS_DB_NAME: "scottclark"
          WORDPRESS_DB_USER: "scottclark"
          WORDPRESS_DB_PASSWORD: "{{ wordpress_mysql_pass }}"
        volumes:
          - wordpress_data_scottclark:/var/www/html
        labels:
          caddy: dev.scottclark.uk
          caddy.import_0: accesslogs
          caddy.php_fastcgi: !unsafe "{{ upstreams 9000 }}"
          caddy.root: "* /var/www/html"
          caddy.file_server: ""
          caddy.encode: gzip
          caddy.@forbidden.path: "/.user.ini"
          caddy.respond: "@forbidden 404"
    - name: Create dev.scottclark.uk ANAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: dev.scottclark.uk
          type: ANAME
          aname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200