---
- name: install seerr on docker0.srv.3fr.uk
  hosts: docker0.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: seerr
        image: ghcr.io/seerr-team/seerr:latest
        pull: true
        init: true
        hostname: seerr
        restart_policy: always
        networks:
          - name: web
        env:
          TZ: "Europe/London"
        volumes:
          - seerr_data:/app/config
        labels:
          caddy_1: seerr.home.thunderweb.uk
          caddy_1.import: accesslogs
          caddy_1.reverse_proxy: !unsafe "{{ upstreams 5055 }}"
          caddy_2: overseerr.home.thunderweb.uk
          caddy_2.redir: https://seerr.home.thunderweb.uk{uri}
        healthcheck:
          test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
          start_period: 20s
          timeout: 3s
          interval: 15s
          retries: 3
    - name: Create seerr.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: seerr.home.thunderweb.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200