---
- name: install IT Tools on docker0
  hosts: docker0.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: ittools
        image: ghcr.io/corentinth/it-tools:latest
        pull: true
        hostname: ittools
        restart_policy: always
        networks:
          - name: web
        labels:
          caddy: tools.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.import_1: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 80 }}"
    - name: Create tools.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: tools.home.thunderweb.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200