---
- name: install calibre-web on docker0
  hosts: docker0.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: calibre-web
        image: lscr.io/linuxserver/calibre-web:latest
        pull: true
        hostname: calibre-web
        restart_policy: always
        networks:
          - name: web
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
          DOCKER_MODS: "linuxserver/mods:universal-calibre"
        volumes:
          - calibre_config:/config
          - /data/shared/eBooks/Calibre:/books
          - /data:/data
        labels:
          caddy: calibre.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.import_1: accesslogs
          caddy.handle: "/opds/*"
          caddy.handle.reverse_proxy: !unsafe "{{ upstreams 8083 }}"
          caddy.handle.reverse_proxy.header_up: 'Authorization "Basic: {{ calibre_hash }}"'
          caddy.reverse_proxy: !unsafe "{{ upstreams 8083 }}"
    - name: Create calibre.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: calibre.home.thunderweb.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200