---
- name: install prowlarr on docker0.srv.3fr.uk
  hosts: docker0.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: prowlarr
        image: lscr.io/linuxserver/prowlarr:latest
        pull: true
        hostname: prowlarr
        restart_policy: always
        networks:
          - name: web
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - prowlarr_data:/config
        labels:
          caddy: prowlarr.home.thunderweb.uk
          caddy.import_0: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 9696 }}"
    - name: Create prowlarr.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: prowlarr.home.thunderweb.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200
