---
- name: install speedtest-tracker on docker0
  hosts: docker0.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: speedtest
        image: lscr.io/linuxserver/speedtest-tracker:latest
        pull: true
        hostname: speedtest
        restart_policy: always
        networks:
          - name: web
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
          DB_CONNECTION: "sqlite"
          APP_KEY: "{{ speedtest_appkey }}"
          SPEEDTEST_SCHEDULE: "0 */8 * * *"
        volumes:
          - speedtest_data:/config
        labels:
          caddy: speedtest.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.import_1: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 80 }}"
    - name: Create speedtest.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: speedtest.home.thunderweb.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200