---
- name: install dozzle on mgmt
  hosts: mgmt.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: dozzle
        image: amir20/dozzle:latest
        pull: true
        hostname: dozzle
        restart_policy: always
        networks:
          - name: web
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        env:
          DOZZLE_REMOTE_AGENT: "webapps.srv.3fr.uk:7007,public.srv.3fr.uk:7007,auth.srv.3fr.uk:7007,cloudflare.srv.3fr.uk:7007,webdev.srv.3fr.uk:7007,plex.srv.3fr.uk:7007,docker1.srv.3fr.uk:7007,docker2.srv.3fr.uk:7007,nas1.srv.3fr.uk:7007,dns.srv.3fr.uk:7007,vps1.wg.3fr.uk:7007,vps2.wg.3fr.uk:7007"
        labels:
          caddy: dozzle.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.import_1: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 8080 }}"
    - name: Create dozzle.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: dozzle.home.thunderweb.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200