---
- name: install munin on monitoring
  hosts: monitoring.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: munin
        image: registry.srv.3fr.uk/munin
        pull: true
        hostname: munin
        restart_policy: always
        networks:
          - name: web
        env:
          NODES: "mgmt.srv.3fr.uk:192.168.250.253 mailgateway1.srv.3fr.uk:192.168.250.25 nas1.srv.3fr.uk:192.168.250.101 docker1.srv.3fr.uk:192.168.250.11 docker0.srv.3fr.uk:192.168.250.10 dns.srv.3fr.uk:192.168.250.53 proxmox1.srv.3fr.uk:192.168.250.111 proxmox2.srv.3fr.uk:192.168.250.112 proxmox3.srv.3fr.uk:192.168.250.113 mini0.srv.3fr.uk:192.168.250.160 vps1.thunderweb.uk:192.168.2.2 vps2.thunderweb.uk:192.168.2.3 auth.srv.3fr.uk:192.168.250.51 public.srv.3fr.uk:192.168.250.90"
          TZ: "Europe/London"
        volumes:
          - munin_config:/etc/munin/munin-conf.d
          - munin_plugin:/etc/munin/plugin-conf.d
          - munin_lib:/var/lib/munin
          - munin_log:/var/log/munin
        labels:
          caddy: munin.home.thunderweb.uk
          caddy.reverse_proxy: !unsafe "{{ upstreams 80 }}"
          caddy.redir: / https://munin.home.thunderweb.uk/munin/
    - name: Create munin.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: munin.home.thunderweb.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200
