---
- name: install reaparr on plex.srv.3fr.uk
  hosts: plex.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: reaparr
        image: reaparr/reaparr:latest
        pull: true
        hostname: reaparr
        restart_policy: always
        networks:
          - name: web
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - reaparr_data:/Config
          - /data/media/downloads:/Downloads
          - /data/media/Movies:/Movies
          - /data/media/TV:/TvShows
        labels:
          caddy: reaparr.home.thunderweb.uk
          caddy.import_0: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 7000 }}"
    - name: Create reaparr.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: reaparr.home.thunderweb.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200