---
- name: install shlink on vps2
  hosts: vps2.wg.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: shlink
        image: shlinkio/shlink:stable
        pull: true
        restart_policy: always
        hostname: shlink
        networks:
          - name: web
        env:
          DEFAULT_DOMAIN: "yag.me.uk"
          IS_HTTPS_ENABLED: "true"
          DB_DRIVER: "mysql"
          DB_USER: "shlink"
          DB_PASSWORD: "{{ shlink_mysql_pass }}"
          DB_NAME: "shlink"
          DB_HOST: "mariadb"
          GEOLITE_LICENSE_KEY: "{{ shlink_geolite }}"
          DISABLE_TRACKING_FROM: "185.241.225.204,79.99.41.143"
          ANONYMIZE_REMOTE_ADDR: "false"
        labels:
          caddy: yag.me.uk www.yag.me.uk
          caddy.reverse_proxy: !unsafe "{{ upstreams 8080 }}"
          caddy.import_0: accesslogs